language: python
python:
  - "3.5"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - DB=postgresql
  - FLASK_APP=run.py
 before_script:
  - psql -c 'create database weconnect_testing;' -U postgres
  - flask db upgrade
script: 
  - nosetests --with-coverage --cover-package=src
  - coveralls
branches:
  except:
  - master
  - challenge2
  - dev
  - challenge1
  only:
  - challenge3
after_success:
 - coveralls
notifications:
  slack:
    on_success: never
    on_failure: never
  email: false